version: 2
updates:
  # Root dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 10
    groups:
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
      production-dependencies:
        dependency-type: "production"
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "automerge"
    assignees:
      - "benedikt-thomma"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # Apps dependencies
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "app:web"

  - package-ecosystem: "npm"
    directory: "/apps/admin"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "app:admin"

  - package-ecosystem: "npm"
    directory: "/apps/mobile"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "app:mobile"
    ignore:
      # Don't update React Native automatically
      - dependency-name: "react-native"
      - dependency-name: "expo"

  # Packages dependencies
  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "package:core"

  - package-ecosystem: "npm"
    directory: "/packages/ui"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "package:ui"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"