version: '3.9'

services:
  # === WEB APP (Customer PWA) ===
  web:
    build:
      context: .
      dockerfile: ./infrastructure/docker/Dockerfile.web
      args:
        - NODE_ENV=development
    container_name: eatech-web
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app/apps/web
      - ./packages:/app/packages
      - web_node_modules:/app/apps/web/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    networks:
      - eatech-network
    depends_on:
      - firebase-emulator

  # === ADMIN DASHBOARD ===
  admin:
    build:
      context: .
      dockerfile: ./infrastructure/docker/Dockerfile.admin
      args:
        - NODE_ENV=development
    container_name: eatech-admin
    ports:
      - "3001:3001"
    volumes:
      - ./apps/admin:/app/apps/admin
      - ./packages:/app/packages
      - admin_node_modules:/app/apps/admin/node_modules
    environment:
      - NODE_ENV=development
      - VITE_APP_URL=http://localhost:3001
    networks:
      - eatech-network
    depends_on:
      - firebase-emulator

  # === MASTER CONTROL ===
  master:
    build:
      context: .
      dockerfile: ./infrastructure/docker/Dockerfile.master
      args:
        - NODE_ENV=development
    container_name: eatech-master
    ports:
      - "3002:3002"
    volumes:
      - ./apps/master:/app/apps/master
      - ./packages:/app/packages
      - master_node_modules:/app/apps/master/node_modules
    environment:
      - NODE_ENV=development
      - VITE_APP_URL=http://localhost:3002
    networks:
      - eatech-network
    depends_on:
      - firebase-emulator

  # === KITCHEN DISPLAY ===
  kitchen:
    build:
      context: .
      dockerfile: ./infrastructure/docker/Dockerfile.kitchen
      args:
        - NODE_ENV=development
    container_name: eatech-kitchen
    ports:
      - "3003:3003"
    volumes:
      - ./apps/kitchen:/app/apps/kitchen
      - ./packages:/app/packages
      - kitchen_node_modules:/app/apps/kitchen/node_modules
    environment:
      - NODE_ENV=development
      - VITE_APP_URL=http://localhost:3003
    networks:
      - eatech-network
    depends_on:
      - firebase-emulator

  # === FIREBASE EMULATOR ===
  firebase-emulator:
    build:
      context: .
      dockerfile: ./infrastructure/docker/Dockerfile.firebase-emulator
    container_name: eatech-firebase-emulator
    ports:
      - "4000:4000" # Emulator UI
      - "5001:5001" # Functions
      - "8080:8080" # Firestore
      - "9099:9099" # Auth
      - "9199:9199" # Storage
    volumes:
      - ./firebase.json:/app/firebase.json
      - ./firestore.rules:/app/firestore.rules
      - ./storage.rules:/app/storage.rules
      - firebase_data:/app/.firebase
    environment:
      - FIREBASE_PROJECT=demo-eatech
    networks:
      - eatech-network
    command: firebase emulators:start --only auth,firestore,storage,functions --project demo-eatech

  # === REDIS CACHE ===
  redis:
    image: redis:7-alpine
    container_name: eatech-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - eatech-network
    command: redis-server --appendonly yes

  # === NGINX REVERSE PROXY ===
  nginx:
    image: nginx:alpine
    container_name: eatech-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infrastructure/nginx/sites:/etc/nginx/sites-available
      - nginx_ssl:/etc/nginx/ssl
    networks:
      - eatech-network
    depends_on:
      - web
      - admin
      - master
      - kitchen

  # === MONITORING (Optional) ===
  prometheus:
    image: prom/prometheus:latest
    container_name: eatech-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - eatech-network
    profiles:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: eatech-grafana
    ports:
      - "3004:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infrastructure/monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - eatech-network
    profiles:
      - monitoring

# === VOLUMES ===
volumes:
  web_node_modules:
  admin_node_modules:
  master_node_modules:
  kitchen_node_modules:
  firebase_data:
  redis_data:
  nginx_ssl:
  prometheus_data:
  grafana_data:

# === NETWORKS ===
networks:
  eatech-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
