# Netlify Configuration for EATECH V3.0

[build]
  # Base directory
  base = "/"
  
  # Build command
  command = "npm run build"
  
  # Publish directory
  publish = "apps/web/dist"
  
  # Node version
  environment = { NODE_VERSION = "18.19.0" }

[build.environment]
  # Build-time environment variables
  NEXT_TELEMETRY_DISABLED = "1"
  TURBO_TOKEN = "dummy"
  TURBO_TEAM = "eatech"

# Context-specific settings
[context.production]
  environment = { NODE_ENV = "production" }

[context.staging]
  environment = { NODE_ENV = "staging" }

[context.develop]
  environment = { NODE_ENV = "development" }

# Redirects
[[redirects]]
  from = "/api/*"
  to = "https://api.eatech.ch/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/admin"
  to = "https://admin.eatech.ch"
  status = 301
  force = true

[[redirects]]
  from = "/master"
  to = "https://master.eatech.ch"
  status = 301
  force = true

# PWA redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Content-Type = "application/manifest+json"

# Functions (if using Netlify Functions)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs]
    output_path = "reports/lighthouse.html"
    
    [plugins.inputs.thresholds]
      performance = 0.9
      accessibility = 0.9
      best-practices = 0.9
      seo = 0.9
      pwa = 0.9

[[plugins]]
  package = "netlify-plugin-cache"
  
  [plugins.inputs]
    paths = [
      "node_modules",
      ".turbo",
      "apps/web/.next/cache"
    ]

# Edge Functions
[[edge_functions]]
  function = "geolocation"
  path = "/api/location"

[[edge_functions]]
  function = "ab-testing"
  path = "/*"
