# EATECH V3.0 - Admin Dashboard Kubernetes Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eatech-admin
  namespace: eatech-prod
  labels:
    app: eatech-admin
    version: v1
    app.kubernetes.io/name: eatech-admin
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: admin-dashboard
    app.kubernetes.io/part-of: eatech-platform
    app.kubernetes.io/managed-by: kubectl
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: eatech-admin
      version: v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: eatech-admin
        version: v1
        app.kubernetes.io/name: eatech-admin
        app.kubernetes.io/instance: production
        app.kubernetes.io/component: admin-dashboard
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: eatech-admin
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        fsGroup: 101
      containers:
      - name: admin
        image: ${DOCKER_REGISTRY}/eatech-admin:${VERSION}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: VITE_FIREBASE_API_KEY
          valueFrom:
            secretKeyRef:
              name: eatech-firebase-secrets
              key: api-key
        - name: VITE_FIREBASE_AUTH_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: eatech-firebase-config
              key: auth-domain
        - name: VITE_FIREBASE_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: eatech-firebase-config
              key: project-id
        - name: VITE_FIREBASE_STORAGE_BUCKET
          valueFrom:
            configMapKeyRef:
              name: eatech-firebase-config
              key: storage-bucket
        - name: VITE_FIREBASE_MESSAGING_SENDER_ID
          valueFrom:
            configMapKeyRef:
              name: eatech-firebase-config
              key: messaging-sender-id
        - name: VITE_FIREBASE_APP_ID
          valueFrom:
            secretKeyRef:
              name: eatech-firebase-secrets
              key: app-id
        - name: VITE_SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: eatech-monitoring-secrets
              key: sentry-dsn-admin
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: eatech-admin-secrets
              key: session-secret
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 30
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 101
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - eatech-admin
              topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: eatech-admin
      imagePullSecrets:
      - name: docker-registry-secret
---
# ServiceAccount for Admin Dashboard
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eatech-admin
  namespace: eatech-prod
  labels:
    app: eatech-admin
    app.kubernetes.io/name: eatech-admin
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: admin-dashboard
---
# Role for Admin Dashboard
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eatech-admin-role
  namespace: eatech-prod
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
# RoleBinding for Admin Dashboard
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eatech-admin-rolebinding
  namespace: eatech-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eatech-admin-role
subjects:
- kind: ServiceAccount
  name: eatech-admin
  namespace: eatech-prod
---
# PodDisruptionBudget for Admin Dashboard
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: eatech-admin-pdb
  namespace: eatech-prod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: eatech-admin
---
# HorizontalPodAutoscaler for Admin Dashboard
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: eatech-admin-hpa
  namespace: eatech-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eatech-admin
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30
      selectPolicy: Max
