# EATECH V3.0 - Docker Compose for Production
version: '3.9'

services:
  # Web Application (Customer Frontend)
  web:
    image: ${DOCKER_REGISTRY}/eatech-web:${VERSION:-latest}
    container_name: eatech-web-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
      - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
      - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
      - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
      - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
      - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
      - VITE_STRIPE_PUBLIC_KEY=${VITE_STRIPE_PUBLIC_KEY}
      - VITE_TWINT_MERCHANT_ID=${VITE_TWINT_MERCHANT_ID}
      - VITE_SENTRY_DSN=${VITE_SENTRY_DSN}
      - VITE_PLAUSIBLE_DOMAIN=${VITE_PLAUSIBLE_DOMAIN}
    networks:
      - eatech-prod-network
    restart: always
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Admin Dashboard
  admin:
    image: ${DOCKER_REGISTRY}/eatech-admin:${VERSION:-latest}
    container_name: eatech-admin-prod
    ports:
      - "3001:8080"
    environment:
      - NODE_ENV=production
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
      - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
      - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
      - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
      - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
      - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
      - VITE_SENTRY_DSN=${VITE_SENTRY_DSN}
    networks:
      - eatech-prod-network
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Master Control Panel
  master:
    image: ${DOCKER_REGISTRY}/eatech-master:${VERSION:-latest}
    container_name: eatech-master-prod
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
      - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
      - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
      - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
      - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
      - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
      - VITE_MASTER_API_KEY=${VITE_MASTER_API_KEY}
      - VITE_SENTRY_DSN=${VITE_SENTRY_DSN}
    networks:
      - eatech-prod-network
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Kitchen Display
  kitchen:
    image: ${DOCKER_REGISTRY}/eatech-kitchen:${VERSION:-latest}
    container_name: eatech-kitchen-prod
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
      - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
      - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
      - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
      - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
      - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
    networks:
      - eatech-prod-network
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # PostgreSQL Database (Managed in production - use Cloud SQL)
  # Uncomment only for self-hosted deployments
  # postgres:
  #   image: postgres:16-alpine
  #   container_name: eatech-postgres-prod
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_prod_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=eatech_prod
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #   networks:
  #     - eatech-prod-network
  #   restart: always

  # Redis Cache (Production)
  redis:
    image: redis:7-alpine
    container_name: eatech-redis-prod
    ports:
      - "6379:6379"
    volumes:
      - redis_prod_data:/data
    command: >
      redis-server
      --appendonly yes
      --requirepass ${REDIS_PASSWORD}
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    networks:
      - eatech-prod-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx Load Balancer
  nginx:
    image: nginx:alpine
    container_name: eatech-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx_cache:/var/cache/nginx
    depends_on:
      - web
      - admin
      - master
      - kitchen
    networks:
      - eatech-prod-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Monitoring - Prometheus Node Exporter
  node-exporter:
    image: prom/node-exporter:latest
    container_name: eatech-node-exporter
    ports:
      - "9100:9100"
    networks:
      - eatech-prod-network
    restart: always
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.1'
          memory: 128M

  # Monitoring - cAdvisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: eatech-cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - eatech-prod-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M

  # Backup Service
  backup:
    image: ${DOCKER_REGISTRY}/eatech-backup:${VERSION:-latest}
    container_name: eatech-backup-prod
    environment:
      - BACKUP_SCHEDULE=${BACKUP_SCHEDULE:-0 3 * * *}
      - POSTGRES_CONNECTION_STRING=${POSTGRES_CONNECTION_STRING}
      - FIREBASE_SERVICE_ACCOUNT=${FIREBASE_SERVICE_ACCOUNT}
      - BACKUP_BUCKET=${BACKUP_BUCKET}
      - RETENTION_DAYS=${RETENTION_DAYS:-30}
    volumes:
      - backup_data:/backups
    networks:
      - eatech-prod-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M

networks:
  eatech-prod-network:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 10.0.0.0/24

volumes:
  postgres_prod_data:
    driver: local
  redis_prod_data:
    driver: local
  nginx_cache:
    driver: local
  backup_data:
    driver: local
