# EATECH V3.0 - Web Application Kubernetes Service
apiVersion: v1
kind: Service
metadata:
  name: eatech-web
  namespace: eatech-prod
  labels:
    app: eatech-web
    app.kubernetes.io/name: eatech-web
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: eatech-platform
    app.kubernetes.io/managed-by: kubectl
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: eatech-web
    version: v1
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
---
# Headless Service for StatefulSet (if needed in future)
apiVersion: v1
kind: Service
metadata:
  name: eatech-web-headless
  namespace: eatech-prod
  labels:
    app: eatech-web
    app.kubernetes.io/name: eatech-web-headless
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: eatech-web
    version: v1
---
# Service for Canary Deployments
apiVersion: v1
kind: Service
metadata:
  name: eatech-web-canary
  namespace: eatech-prod
  labels:
    app: eatech-web
    variant: canary
    app.kubernetes.io/name: eatech-web-canary
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: eatech-web
    version: v2-canary
---
# ServiceMonitor for Prometheus
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eatech-web
  namespace: eatech-prod
  labels:
    app: eatech-web
    release: prometheus
spec:
  selector:
    matchLabels:
      app: eatech-web
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
# EndpointSlice for better performance (K8s 1.21+)
apiVersion: v1
kind: Endpoints
metadata:
  name: eatech-web-external
  namespace: eatech-prod
  labels:
    app: eatech-web
    type: external
subsets:
- addresses:
  - ip: 10.0.1.10  # Example external backend
  - ip: 10.0.1.11
  ports:
  - name: http
    port: 80
    protocol: TCP
