# EATECH V3.0 - Kubernetes Secrets Configuration
# SECURITY WARNING: This file contains templates for secrets
# Replace all placeholder values with actual secrets before deployment
# Use sealed-secrets or external secret management in production

# Main Application Secrets
apiVersion: v1
kind: Secret
metadata:
  name: eatech-secrets
  namespace: eatech-production
  labels:
    app: eatech
    component: secrets
    environment: production
  annotations:
    description: "Main EATECH application secrets"
    rotation-policy: "90-days"
    encryption-at-rest: "enabled"
type: Opaque
data:
  # Firebase Configuration (base64 encoded JSON)
  firebase-config: eyJwcm9qZWN0SWQiOiJlYXRlY2gtcHJvZCIsInN0b3JhZ2VCdWNrZXQiOiJlYXRlY2gtcHJvZC5hcHBzcG90LmNvbSIsImFwaUtleSI6IkFJemFTeXh4eCIsImF1dGhEb21haW4iOiJlYXRlY2gtcHJvZC5maXJlYmFzZWFwcC5jb20ifQ==

  # Stripe Payment Keys
  stripe-secret-key: c2tfbGl2ZV9wbGFjZWhvbGRlcl9zdHJpcGVfc2VjcmV0X2tleQ==
  stripe-publishable-key: cGtfbGl2ZV9wbGFjZWhvbGRlcl9zdHJpcGVfcHVibGlzaGFibGVfa2V5
  stripe-webhook-secret: d2hzZWNfcGxhY2Vob2xkZXJfc3RyaXBlX3dlYmhvb2tfc2VjcmV0

  # Twilio SMS/WhatsApp
  twilio-account-sid: QUNwbGFjZWhvbGRlcnR3aWxpb2FjY291bnRzaWQ=
  twilio-auth-token: cGxhY2Vob2xkZXJfdHdpbGlvX2F1dGhfdG9rZW4=
  twilio-phone-number: KzQxNzkxMjM0NTY3

  # SendGrid Email
  sendgrid-api-key: U0cuUExBQ0VIT0xERVIuWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWA==
  sendgrid-from-email: bm9yZXBseUBlYXRlY2guY2g=

  # OpenAI API
  openai-api-key: c2stcGxhY2Vob2xkZXJfb3BlbmFpX2FwaV9rZXk=
  openai-organization: b3JnLXBsYWNlaG9sZGVyX29wZW5haV9vcmc=

  # Database Passwords
  redis-password: cmVkaXNfc2VjdXJlX3Bhc3N3b3JkXzEyMw==
  postgres-password: cG9zdGdyZXNfc2VjdXJlX3Bhc3N3b3JkXzEyMw==
  postgres-url: cG9zdGdyZXNxbDovL2VhdGVjaDpwYXNzd29yZEBlYXRlY2gtcG9zdGdyZXMtc2VydmljZTo1NDMyL2VhdGVjaF9hbmFseXRpY3M=
  redis-url: cmVkaXM6Ly86cmVkaXNfc2VjdXJlX3Bhc3N3b3JkXzEyM0BlYXRlY2gtcmVkaXMtc2VydmljZTo2Mzc5

  # Security Keys
  jwt-secret: and0X3NlY3VyZV9yYW5kb21fc2VjcmV0X2tleV8xMjM0NTY3ODkw
  encryption-key: ZW5jcnlwdGlvbl9zZWN1cmVfcmFuZG9tX2tleV8xMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
  cookie-secret: Y29va2llX3NlY3VyZV9yYW5kb21fc2VjcmV0XzEyMzQ1Njc4OTA=
  session-secret: c2Vzc2lvbl9zZWN1cmVfcmFuZG9tX3NlY3JldF8xMjM0NTY3ODkw

  # Monitoring & Analytics
  sentry-dsn: aHR0cHM6Ly9wbGFjZWhvbGRlckBvMTIzNDU2LmluZ2VzdC5zZW50cnkuaW8vMTIzNDU2
  sentry-dsn-admin: aHR0cHM6Ly9wbGFjZWhvbGRlci1hZG1pbkBvMTIzNDU2LmluZ2VzdC5zZW50cnkuaW8vMTIzNDU3
  sentry-dsn-master: aHR0cHM6Ly9wbGFjZWhvbGRlci1tYXN0ZXJAB8MTIzNDU2LmluZ2VzdC5zZW50cnkuaW8vMTIzNDU4
  sentry-dsn-functions: aHR0cHM6Ly9wbGFjZWhvbGRlci1mdW5jdGlvbnNAb8MTIzNDU2LmluZ2VzdC5zZW50cnkuaW8vMTIzNDU5

  # Analytics
  mixpanel-token: cGxhY2Vob2xkZXJfbWl4cGFuZWxfdG9rZW4=
  plausible-api-key: cGxhY2Vob2xkZXJfcGxhdXNpYmxlX2FwaV9rZXk=

  # External Service URLs
  webhook-url-stripe: aHR0cHM6Ly9hcGkuZWF0ZWNoLmNoL3dlYmhvb2tzL3N0cmlwZQ==
  webhook-url-twilio: aHR0cHM6Ly9hcGkuZWF0ZWNoLmNoL3dlYmhvb2tzL3R3aWxpbw==

---
# Firebase Service Account Secret
apiVersion: v1
kind: Secret
metadata:
  name: firebase-service-account
  namespace: eatech-production
  labels:
    app: eatech
    component: firebase-credentials
  annotations:
    description: "Firebase service account credentials"
type: Opaque
data:
  # Firebase service account JSON (base64 encoded)
  service-account.json: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiZWF0ZWNoLXByb2QiLAogICJwcml2YXRlX2tleV9pZCI6ICJwbGFjZWhvbGRlcl9rZXlfaWQiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cblBMQUNFSE9MREVSIFBSSVZBVEU8S0VZXG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAiZmlyZWJhc2UtYWRtaW5zZGtAZWF0ZWNoLXByb2QuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAicGxhY2Vob2xkZXJfY2xpZW50X2lkIiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9maXJlYmFzZS1hZG1pbnNka0BlYXRlY2gtcHJvZC5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIKfQ==

---
# TLS Certificates
apiVersion: v1
kind: Secret
metadata:
  name: eatech-tls-certificate
  namespace: eatech-production
  labels:
    app: eatech
    component: tls-certificate
  annotations:
    description: "TLS certificate for main domains"
    cert-manager.io/issuer: "letsencrypt-prod"
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZYVENDQkVXZ0F3SUJBZ0lVUExBQ0VIT0xERVIuLi4KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQWtJQkFRQ25wUExBQ0VIT0xERVIuLi4KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQ==

---
# Admin TLS Certificate with Client Authentication
apiVersion: v1
kind: Secret
metadata:
  name: eatech-admin-tls-certificate
  namespace: eatech-production
  labels:
    app: eatech-admin
    component: tls-certificate
    security-level: high
  annotations:
    description: "TLS certificate for admin dashboard"
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZYVENDQkVXZ0F3SUJBZ0lVQURNSU4uLi4KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQWtJQkFRQ25wQURNSU4uLi4KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQ==

---
# Master Control TLS Certificate with Maximum Security
apiVersion: v1
kind: Secret
metadata:
  name: eatech-master-tls-certificate
  namespace: eatech-production
  labels:
    app: eatech-master
    component: tls-certificate
    security-level: maximum
  annotations:
    description: "TLS certificate for master control system"
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZYVENDQkVXZ0F3SUJBZ0lVTUFTVEVSLi4uCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQWtJQkFRQ25wTUFTVEVSLi4uCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=

---
# CDN TLS Certificate
apiVersion: v1
kind: Secret
metadata:
  name: eatech-cdn-tls-certificate
  namespace: eatech-production
  labels:
    app: eatech-cdn
    component: tls-certificate
  annotations:
    description: "TLS certificate for CDN"
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZYVENDQkVXZ0F3SUJBZ0lVQ0ROLi4uCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQWtJQkFRQ25wQ0ROLi4uCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=

---
# Client CA Certificate for Master Control Authentication
apiVersion: v1
kind: Secret
metadata:
  name: eatech-master-client-ca
  namespace: eatech-production
  labels:
    app: eatech-master
    component: client-ca
    security-level: maximum
  annotations:
    description: "Client CA certificate for master control authentication"
type: Opaque
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURYVENDQWtXZ0F3SUJBZ0lVQ0xJRU5ULi4uCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=

---
# Master Control Enhanced Secrets
apiVersion: v1
kind: Secret
metadata:
  name: eatech-master-secrets
  namespace: eatech-production
  labels:
    app: eatech-master
    component: master-secrets
    security-level: maximum
  annotations:
    description: "Enhanced secrets for master control system"
type: Opaque
data:
  # Master Control Keys
  master-control-key: bWFzdGVyX2NvbnRyb2xfc2VjdXJlX3JhbmRvbV9rZXlfMTIzNDU2Nzg5MA==
  api-url: aHR0cHM6Ly9hcGkuZWF0ZWNoLmNoXG4=
  encryption-key: bWFzdGVyX2VuY3J5cHRpb25fc2VjdXJlX3JhbmRvbV9rZXlfMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
  jwt-secret: bWFzdGVyX2p3dF9zZWN1cmVfcmFuZG9tX3NlY3JldF8xMjM0NTY3ODkw
  audit-key: bWFzdGVyX2F1ZGl0X3NlY3VyZV9yYW5kb21fa2V5XzEyMzQ1Njc4OTA=
  sentry-dsn-master: aHR0cHM6Ly9tYXN0ZXItcGxhY2Vob2xkZXJAb8MTIzNDU2LmluZ2VzdC5zZW50cnkuaW8vMTIzNDU4
  security-alert-webhook: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvUExBQ0VIT0xERVIvU0VDVVJJVFkvQUxFUlQ=
  audit-endpoint: aHR0cHM6Ly9hdWRpdC5lYXRlY2guY2gvYXBpL2xvZ3M=
  audit-encryption-key: YXVkaXRfZW5jcnlwdGlvbl9zZWN1cmVfcmFuZG9tX2tleV8xMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=

---
# Docker Registry Secret
apiVersion: v1
kind: Secret
metadata:
  name: eatech-registry-secret
  namespace: eatech-production
  labels:
    app: eatech
    component: registry-credentials
  annotations:
    description: "Docker registry credentials"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5lYXRlY2guY2giOnsidXNlcm5hbWUiOiJlYXRlY2giLCJwYXNzd29yZCI6InJlZ2lzdHJ5X3Bhc3N3b3JkXzEyMyIsImF1dGgiOiJaV0YwWldOb09uSmxaMmx6ZEhKNVgzQmhjM04zYjNKa1h6RXlNdz09In19fQ==

---
# Basic Auth Secret for Admin Dashboard
apiVersion: v1
kind: Secret
metadata:
  name: eatech-admin-auth
  namespace: eatech-production
  labels:
    app: eatech-admin
    component: basic-auth
    security-level: high
  annotations:
    description: "Basic auth credentials for admin dashboard"
type: Opaque
data:
  auth: YWRtaW46JGFwcjEkSDY1NDRGZ0wkOXNyQ25GMnh3QTNYU2pSc2hNYVdPLg==  # admin:admin123

---
# NGINX Security Configuration Secret
apiVersion: v1
kind: Secret
metadata:
  name: nginx-security-config
  namespace: eatech-production
  labels:
    app: eatech
    component: nginx-security
  annotations:
    description: "NGINX security configuration"
type: Opaque
data:
  security.conf: IyBOZ2lueCBTZWN1cml0eSBDb25maWd1cmF0aW9uCmFkZF9oZWFkZXIgWC1GcmFtZS1PcHRpb25zICJTQU1FT1JJR0lOIiBhbHdheXM7CmFkZF9oZWFkZXIgWC1YU1MtUHJvdGVjdGlvbiAiMTsgbW9kZT1ibG9jayIgYWx3YXlzOw==

---
# Monitoring Secrets
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secrets
  namespace: eatech-production
  labels:
    app: eatech-monitoring
    component: monitoring-credentials
  annotations:
    description: "Monitoring system credentials"
type: Opaque
data:
  # Grafana
  grafana-admin-password: Z3JhZmFuYV9hZG1pbl9wYXNzd29yZF8xMjM=
  grafana-secret-key: Z3JhZmFuYV9zZWNyZXRfa2V5XzEyMzQ1Njc4OTA=

  # Prometheus
  prometheus-admin-password: cHJvbWV0aGV1c19hZG1pbl9wYXNzd29yZF8xMjM=

  # AlertManager
  alertmanager-webhook-url: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvQUxFUlRNQU5BR0VSL1dFQkhPT0s=

---
# AI Service Secrets
apiVersion: v1
kind: Secret
metadata:
  name: ai-service-secrets
  namespace: eatech-production
  labels:
    app: eatech-ai
    component: ai-credentials
  annotations:
    description: "AI service credentials and keys"
type: Opaque
data:
  # OpenAI
  openai-api-key: c2stcGxhY2Vob2xkZXJfb3BlbmFpX2FwaV9rZXk=
  openai-organization: b3JnLXBsYWNlaG9sZGVyX29wZW5haV9vcmc=

  # Google Vision API
  google-vision-credentials: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiZWF0ZWNoLXZpc2lvbiIKfQ==

  # Azure Cognitive Services
  azure-cognitive-key: YXp1cmVfY29nbml0aXZlX3BsYWNlaG9sZGVyX2tleQ==
  azure-cognitive-endpoint: aHR0cHM6Ly9lYXRlY2gtY29nbml0aXZlLmNvZ25pdGl2ZXNlcnZpY2VzLmF6dXJlLmNvbS8=

---
# Backup and Recovery Secrets
apiVersion: v1
kind: Secret
metadata:
  name: backup-secrets
  namespace: eatech-production
  labels:
    app: eatech-backup
    component: backup-credentials
  annotations:
    description: "Backup and recovery credentials"
type: Opaque
data:
  # AWS S3 for backups
  aws-access-key-id: QUtJQVBMQUNFSE9MREVSX0FXU19BQ0NFU1NfS0VZ
  aws-secret-access-key: cGxhY2Vob2xkZXJfYXdzX3NlY3JldF9hY2Nlc3Nfa2V5XzEyMzQ1Njc4OTA=
  aws-region: ZXVyb3BlLXdlc3QtMw==

  # Encryption key for backups
  backup-encryption-key: YmFja3VwX2VuY3J5cHRpb25fc2VjdXJlX3JhbmRvbV9rZXlfMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=

---
# External Service Integration Secrets
apiVersion: v1
kind: Secret
metadata:
  name: external-integration-secrets
  namespace: eatech-production
  labels:
    app: eatech
    component: external-integrations
  annotations:
    description: "External service integration credentials"
type: Opaque
data:
  # Mapbox
  mapbox-access-token: cGtfcGxhY2Vob2xkZXJfbWFwYm94X2FjY2Vzc190b2tlbg==

  # Cloudflare
  cloudflare-api-token: Y2xvdWRmbGFyZV9hcGlfdG9rZW5fcGxhY2Vob2xkZXI=
  cloudflare-zone-id: Y2xvdWRmbGFyZV96b25lX2lkX3BsYWNlaG9sZGVy

  # PostFinance
  postfinance-merchant-id: UEZfTUVSQ0hBTlRfSURfUExBQ0VIT0xERVI=
  postfinance-api-key: cG9zdGZpbmFuY2VfYXBpX2tleV9wbGFjZWhvbGRlcg==

  # TWINT
  twint-certificate: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tClRXSU5UX0NFUlRJRklDQVRFX1BMQUNFSE9MREVSCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
  twint-private-key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tClRXSU5UX1BSSVZBVEVfS0VZX1BMQUNFSE9MREVSCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=
